travis:
  secure:
    BINSTAR_TOKEN: p7UYm7XF4/Zu5DYFv04JCcLOyeOcqRMiQ0xy8zeyMGLcnrJliF+BSgoYZm0l1LwgfaXVjvvnUbqzuBknkGG8XXG3+mcSP1H/xi07JMnbUcK9VPDc2GxjqiOarTuRxEZc6wpu1jRvP3LbSxfHXnYBpFXKhweLZOT9eTeXjjxm3RB5rSfQc95j8vjeGw9XVhh3Yq0ZijVKNifrWk13cjycryBE8+w56xFfLgmo+83kzk3rcINZq1/vKuQuDkqbTgjJAj+CA5IlVNM+Ox8h2uEaunv8qGrfz+7Drnn7T5vuCVmV4HE/ppd3/KGkLNcw5iGjXdR9o1Zzo9eMT5mehnF4GHedes2PTka+7eoMc8RdkkgJZ2X/uDEmninyKVmCXfFkRScPsAbkeW5i1nYNIznkKRknUer2kPepr/Dn6C2yPoUlXghkQb+gTRxdVk6gzVHqbWlTBltnFtNrwFVWwBxAuueUzDNs9CP7ClGwIXs0airj4wlYS+p/0hZEyuCJCIU5QfmHdrRHHxmNZlDtyJtjmnw2XKrtUn3sf73lMHbz0pocCX9qGsYLhsB1VwTOHB114O5Ez+uDs8mPzRjDzuwE41tiijQNNXG8Pik2alvpQS1SYEQkmAX5JjEv6/hCj2y9TmRwDKIn7nUXAgvfo7X8jMo0p1rP8nZZytzbT/JgumQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
